### PR TITLE
Fixes logging and build.sh to work with minv2

### LINKED ISSUE #70: Do not log to file + update perms checks to include /tmp/ssh
https://github.com/Shippable/pm/issues/5250

Cexec should not be logging anything to a file. All logs should go directly to the console where it can be captured by mexec and reported to the jobConsole. There's very little value in having the same content available in a file on the node. Removing the file logger also eliminates the problem of having to manage permissions and cleanup.

### PR DESCRIPTION
**Pull request by rageshkrishna**
Fixes #70 

Verified that ssh-add works and is able to see all the keys we write. `ssh -vT git@github.com` confirms my identity as well. This now works on both minv2 and other images.

### CODE REVIEW

File: build.sh [hunk 1]
```diff
@@ -2,22 +2,23 @@
...
 update_dir() {
   cd $PROGDIR
 }
 
 update_perms() {
-  SUDO=`which sudo`
-  $SUDO mkdir -p /home/shippable/build/logs
   $SUDO mkdir -p /shippableci
-  $SUDO chown -R $USER:$USER /home/shippable/build/logs
-  $SUDO chown -R $USER:$USER /home/shippable/build
```
Comment (rageshkrishna) [inline build.sh]: I don't think we need these any more. @ric03uec ?

Comment (ric03uec) [inline build.sh]: yes, not required now
